version: '3'

services:
  server:
    build: qa_api/
    depends_on:
      - 'database'
    ports:
      - '3000:3000'

  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: questions
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      # - ./qa_api/data:/tmp
      - db_data:/var/lib/mysql
volumes:
  db_data: